version: "3"
services:
  clickhouse-server:
    image: yandex/clickhouse-server
    platform: linux/amd64
    env_file: .env.clickhouse
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8123/ping || exit 1
      interval: 2s
      timeout: 2s
      retries: 16
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./.docker-storage/clickhouse:/var/lib/clickhouse
      - ./.docker-storage/logs:/var/log/clickhouse-server

  clickhouse-client:
    image: yandex/clickhouse-client
    # command: ["--host", "clickhouse-server"]
    # TODO change to infinite sleep - i have seen something like that somewhere
    entrypoint: ["/bin/sleep"]
    command: ["2700000"]
    depends_on:
      clickhouse-server:
        condition: service_healthy
